/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.taptap.tapsdk.bindings.java;

public class Config {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Config(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Config obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TapSDKJNI.delete_Config(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnable_duration_statistics(boolean value) {
    TapSDKJNI.Config_enable_duration_statistics_set(swigCPtr, this, value);
  }

  public boolean getEnable_duration_statistics() {
    return TapSDKJNI.Config_enable_duration_statistics_get(swigCPtr, this);
  }

  public Config() {
    this(TapSDKJNI.new_Config(), true);
  }

}
