/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.taptap.tapsdk.bindings.java;

public class Device {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Device(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Device obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PlatformJNI.delete_Device(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    PlatformJNI.Device_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    PlatformJNI.Device_change_ownership(this, swigCPtr, true);
  }

  public static void SetCurrent(Device device) {
    PlatformJNI.Device_SetCurrent(Device.getCPtr(device), device);
  }

  public static Device GetCurrent() {
    long cPtr = PlatformJNI.Device_GetCurrent();
    return (cPtr == 0) ? null : new Device(cPtr, true);
  }

  public String GetDeviceID() {
    return PlatformJNI.Device_GetDeviceID(swigCPtr, this);
  }

  public String GetCacheDir() {
    return PlatformJNI.Device_GetCacheDir(swigCPtr, this);
  }

  public String GetCaCertDir() {
    return PlatformJNI.Device_GetCaCertDir(swigCPtr, this);
  }

  public Device() {
    this(PlatformJNI.new_Device(), true);
    PlatformJNI.Device_director_connect(this, swigCPtr, true, true);
  }

}
