/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.taptap.tapsdk.bindings.java;

public class Game {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Game(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Game obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TapSDKJNI.delete_Game(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    TapSDKJNI.Game_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    TapSDKJNI.Game_change_ownership(this, swigCPtr, true);
  }

  public static void SetCurrent(Game game) {
    TapSDKJNI.Game_SetCurrent(Game.getCPtr(game), game);
  }

  public static Game GetCurrent() {
    long cPtr = TapSDKJNI.Game_GetCurrent();
    return (cPtr == 0) ? null : new Game(cPtr, true);
  }

  public String GetGameID() {
    return TapSDKJNI.Game_GetGameID(swigCPtr, this);
  }

  public String GetPackageName() {
    return TapSDKJNI.Game_GetPackageName(swigCPtr, this);
  }

  public Game() {
    this(TapSDKJNI.new_Game(), true);
    TapSDKJNI.Game_director_connect(this, swigCPtr, true, true);
  }

}
