/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.taptap.tapsdk.bindings.java;

public class PlatformJNI {
  public final static native void Window_OnForeground();
  public final static native void Window_OnBackground();
  public final static native long new_Window();
  public final static native void delete_Window(long jarg1);
  public final static native void Device_SetCurrent(long jarg1, Device jarg1_);
  public final static native long Device_GetCurrent();
  public final static native String Device_GetDeviceID(long jarg1, Device jarg1_);
  public final static native String Device_GetCacheDir(long jarg1, Device jarg1_);
  public final static native String Device_GetCaCertDir(long jarg1, Device jarg1_);
  public final static native long new_Device();
  public final static native void delete_Device(long jarg1);
  public final static native void Device_director_connect(Device obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void Device_change_ownership(Device obj, long cptr, boolean take_or_release);

  public static String SwigDirector_Device_GetDeviceID(Device jself) {
    return jself.GetDeviceID();
  }
  public static String SwigDirector_Device_GetCacheDir(Device jself) {
    return jself.GetCacheDir();
  }
  public static String SwigDirector_Device_GetCaCertDir(Device jself) {
    return jself.GetCaCertDir();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
