/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.taptap.tapsdk.bindings.java;

public class TDSUser {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected TDSUser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TDSUser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TapSDKJNI.delete_TDSUser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    TapSDKJNI.TDSUser_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    TapSDKJNI.TDSUser_change_ownership(this, swigCPtr, true);
  }

  public static void SetCurrent(TDSUser user) {
    TapSDKJNI.TDSUser_SetCurrent(TDSUser.getCPtr(user), user);
  }

  public static TDSUser GetCurrent() {
    long cPtr = TapSDKJNI.TDSUser_GetCurrent();
    return (cPtr == 0) ? null : new TDSUser(cPtr, true);
  }

  public TDSUser(String user_id) {
    this(TapSDKJNI.new_TDSUser__SWIG_0(user_id), true);
    TapSDKJNI.TDSUser_director_connect(this, swigCPtr, true, true);
  }

  public TDSUser() {
    this(TapSDKJNI.new_TDSUser__SWIG_1(), true);
    TapSDKJNI.TDSUser_director_connect(this, swigCPtr, true, true);
  }

  public String GetUserId() {
    return (getClass() == TDSUser.class) ? TapSDKJNI.TDSUser_GetUserId(swigCPtr, this) : TapSDKJNI.TDSUser_GetUserIdSwigExplicitTDSUser(swigCPtr, this);
  }

  public String GetUserName() {
    return TapSDKJNI.TDSUser_GetUserName(swigCPtr, this);
  }

  public boolean ContainTapInfo() {
    return TapSDKJNI.TDSUser_ContainTapInfo(swigCPtr, this);
  }

}
