name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: install swig
      run: apt-get install swig
      
    - name: move to workspace
      run: cd scripts
    - name: Grant execute permission for build.sh
      run: chmod +x build-android.sh
    - name: Build
      run: ./build-android.sh
