name: Headers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pack Headers
        run: |
          mkdir sdk_headers
          cp source/sdk/*.h  sdk_headers
          zip -r sdk_headers.zip sdk_headers

      - name: Upload Headers
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: sdk_headers.zip
          # A file, directory or wildcard pattern that describes what to upload
          path: sdk_headers.zip

      - name: Upload Headers to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: sdk_headers.zip
          asset_name: sdk_headers.zip
          asset_content_type: application/octet-stream