name: iOS starter workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          brew install ninja
      - name: Build
        run: |
          cd scripts
          chmod +x build-ios.sh
          ./build-ios.sh
          cd ../ios/build/source/sdk
          zip -r sdk.framework.zip sdk.framework

      - name: Upload sdk
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: sdk.framework.zip
          # A file, directory or wildcard pattern that describes what to upload
          path: ios/build/source/sdk/sdk.framework.zip
