name: Linux CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install ninja
        run: sudo apt-get install ninja-build

      - name: install swig
        run: sudo apt-get install swig

      - name: Build
        run: |
          cd scripts
          chmod +x build-host.sh
          ./build-host.sh

      - name: Upload sdk
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: libtds_core.so
          # A file, directory or wildcard pattern that describes what to upload
          path: build/source/sdk/libtds_core.so

      - name: Upload csharp-binding
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: libbindings-csharp.so
          # A file, directory or wildcard pattern that describes what to upload
          path: build/source/bindings/csharp/libbindings-csharp.so

      - name: Upload SDK to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: linux_sdk
          asset_name: build/source/sdk/libtds_core.so
          asset_content_type: application/octet-stream

      - name: Upload Bindings to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/source/bindings/csharp/libbindings-csharp.so
          asset_name: linux_csharp_bindings
          asset_content_type: application/octet-stream
