name: Linux CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install ninja
        run: sudo apt-get install ninja-build

      - name: install swig
        run: sudo apt-get install swig

      - name: Build
        run: |
          cd scripts
          chmod +x build-host.sh
          ./build-host.sh

      - name: Pack sdks
        run: |
          mkdir linux_sdks
          cp build/source/sdk/libtds_core.so  linux_sdks/libtds_core.so
          cp build/source/bindings/csharp/libbindings-csharp.so  linux_sdks/libbindings-csharp.so
          zip -r linux_sdks.zip linux_sdks

      - name: Upload sdk
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: linux_sdks.zip
          # A file, directory or wildcard pattern that describes what to upload
          path: linux_sdks.zip

      - name: Upload SDK to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: linux_sdks.zip
          asset_name: linux_sdks.zip
          asset_content_type: application/octet-stream