name: Linux CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install swig
        run: sudo apt-get install swig

      - name: Build
        run: |
          cd scripts
          chmod +x build-host.sh
          ./build-host.sh

      - name: Upload sdk
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: libtds_core.a
          # A file, directory or wildcard pattern that describes what to upload
          path: build/source/sdk/libtds_core.a

      - name: Upload csharp-binding
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: libcsharp-binding.a
          # A file, directory or wildcard pattern that describes what to upload
          path: build/source/bindings/libcsharp-binding.a
