name: Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        shell: powershell
        run: |
          nuget install swigwintools -Version 4.0.0 -OutputDirectory C:\Tools\swig

      - name: Build
        shell: powershell
        run: |
          $env:PATH="C:\Tools\swig;" + $env:PATH
          $WORKING_DIR=(Get-Location).ToString() -replace "\\","/"
          mkdir build
          cd .\build\
          cmake ../ -G "Visual Studio 17 2022" -A "x64" -DCMAKE_BUILD_TYPE=Release -DCSHARP_BINDING="$WORKING_DIR/swig"
          cmake --build ./ --config Release -j 8

      - name: Upload lib
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: tds_core_static.lib
          # A file, directory or wildcard pattern that describes what to upload
          path: build/source/sdk/Release/tds_core_combined.lib

      - name: Upload dll
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: tds_core.dll
          # A file, directory or wildcard pattern that describes what to upload
          path: build/source/bindings/csharp/Release/bindings-csharp.dll

      - name: Upload dll lib
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: tds_core.dll.lib
          # A file, directory or wildcard pattern that describes what to upload
          path: build/source/bindings/csharp/Release/bindings-csharp.lib